version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.8.0
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:b3:16:4b:58:9a:40:93:1e:21:73:e5:a6:24:bd:88"

      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Build library
          command: yarn build

      - run:
          name: Creating an archive for GitHub release
          command: npm run zip

      - run:
          name: Publishing NPM and GitHub Packages
          command: npm run release
